### ISSUE TITLE
Java trace is not always successful

### ISSUE THREAD

**Issue by rbeezer** [RunestoneInteractive/rs#15]
A significant percentage of the time (25% - 50%?) I get a "bad" trace for a small-ish Java program, the other times the trace is fine.  (I've manually added unthoughtful line breaks to make the original final line readable here.)

```
 allTraceData["sieve-codelens-java"] = com.sun.jdi.VMDisconnectedException
       at com.sun.tools.jdi.TargetVM.waitForReply(TargetVM.java:304)
       at com.sun.tools.jdi.VirtualMachineImpl.waitForTargetReply(VirtualMachineImpl.java:1036)
       at com.sun.tools.jdi.PacketStream.waitForReply(PacketStream.java:69)
       at com.sun.tools.jdi.JDWP$VirtualMachine$Suspend.waitForReply(JDWP.java:570)
       at com.sun.tools.jdi.JDWP$VirtualMachine$Suspend.process(JDWP.java:556)
       at com.sun.tools.jdi.VirtualMachineImpl.suspend(VirtualMachineImpl.java:408)
       at traceprinter.VMCommander.run(VMCommander.java:44)
{"code":"public class SievePrimeFactors  {\n   public static void main(String args[]) 
{\n      int num = 20;\n      boolean[] bool = new boolean[num];\n\n      
for (int i = 0; i< bool.length; i++) {\n         bool[i] = true;\n      }
\n      for (int i = 2; i < Math.sqrt(num); i++) {\n         if(bool[i] == true) 
{\n            for(int j = (i*i); j < num; j = j+i) {\n               bool[j] = false;\n            }\n         }\n      }\n      
System.out.println(\"List of prime numbers: \");\n      
for (int i = 2; i< bool.length; i++) {\n         if(bool[i]==true) 
{\n            System.out.println(i);\n         }\n      }\n   }\n}\n\n","stdin":"",
"trace":[{"line":"0","event":"uncaught_exception","offset":"0","exception_msg":"Success is null?"}],"userlog":"Debugger VM maxMemory: 444M\n"}
```

Input program is just lifted from some programming site, I forget if I made edits.

```java
def SieveOfEratosthenes(n):
   # array of type boolean with True values in it
   prime = [True for i in range(n + 1)]
   p = 2
   while (p * p <= n):
      # If it remain unchanged it is prime
      if (prime[p] == True):
         # updating all the multiples
         for i in range(p * 2, n + 1, p):
            prime[i] = False
      p += 1
   prime[0]= False
   prime[1]= False
   # Print
   for p in range(n + 1):
      if prime[p]:
         print (p,end=" ")
# main
if __name__=='__main__':
   n = 20
   print ("The prime numbers smaller than or equal to", n,"is")
   SieveOfEratosthenes(n)
```

Hitting

```
http://tracer.runestone.academy:5000/tracejava
```

Is the program crappy?  Server needs a fix?  Any certain string I can reliably test for to handle failure for returned trace?

**Comment by bnmnetp** [comment]
Closing. The `VMDisconnectedException` comes out of the Java tracer, which runs as a separate `docker run tracejava` black box maintained outside this project — the same situation as the other codelens tracers. The retry-on-failure idea discussed here was never implemented, and there's no code in this repo that wraps that call.

Three years on with no recurrence reported, closing rather than leaving it open. If flaky Java traces are still happening, a new issue with a current example would be the way to pick it back up.
