### ISSUE TITLE
crasher in removeinstructor

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/rs#311]
Its not clear that this should be removeinstructor -- unless someone made a whole bunch of students instructors.  It seems more like it should be removestudent.

Start at admin.py line 905

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/applications/runestone/controllers/admin.py", line 3029, in 
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/globals.py", line 430, in 
    self._caller = lambda f: f()
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/tools.py", line 4535, in f
    return action(*a, **b)
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/applications/runestone/controllers/admin.py", line 905, in removeinstructor
    ).delete()
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/packages/dal/pydal/objects.py", line 2730, in delete
    ret = db._adapter.delete(table, self.query)
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/packages/dal/pydal/adapters/base.py", line 580, in delete
    sql = self._delete(table, query)
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/packages/dal/pydal/adapters/base.py", line 576, in _delete
    sql_q = self.expand(query, query_env=query_env)
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/packages/dal/pydal/adapters/base.py", line 472, in _expand
    rv = op(first, second, **optional_args)
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/packages/dal/pydal/dialects/base.py", line 276, in _and
    self.expand(first, query_env=query_env),
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/packages/dal/pydal/dialects/__init__.py", line 96, in expand
    return self.adapter.expand(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/packages/dal/pydal/adapters/base.py", line 472, in _expand
    rv = op(first, second, **optional_args)
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/packages/dal/pydal/dialects/base.py", line 430, in eq
    self.expand(second, first.type, query_env=query_env),
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/packages/dal/pydal/dialects/__init__.py", line 96, in expand
    return self.adapter.expand(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/packages/dal/pydal/adapters/base.py", line 482, in _expand
    rv = self.represent(expression, field_type)
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/packages/dal/pydal/adapters/base.py", line 415, in represent
    return super(SQLAdapter, self).represent(obj, field_type)
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/packages/dal/pydal/adapters/base.py", line 369, in represent
    return self.representer.represent(obj, field_type)
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/packages/dal/pydal/representers/__init__.py", line 248, in represent
    rv = self.get_representer_for_type(field_type)(rv, field_type)
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/packages/dal/pydal/representers/__init__.py", line 140, in __call__
    return self.adapt(self.call(value, field_type))
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/packages/dal/pydal/representers/__init__.py", line 134, in _call_with_extras
    return self.inner_call(value, **extras)
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/packages/dal/pydal/representers/__init__.py", line 125, in _inner_call
    return self.obj.f(self.representer, value, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rsptx/web2py_server/gluon/packages/dal/pydal/representers/base.py", line 141, in _reference
    return str(long(value))
ValueError: invalid literal for int() with base 10: 'Some Name'
```

**Comment by bnmnetp** [comment]
Closing as legacy-only. This traceback comes from the web2py `admin/removeinstructor` endpoint, which is reachable only from the old instructor page's JavaScript. That interface is being retired, and we are not patching bugs in it — the equivalent function in the new admin server is `/remove_students`, which builds its query differently and doesn't have this failure mode.

For the record, your instinct in the description was right: the `ValueError: invalid literal for int() with base 10: 'Some Name'` is a name being passed where a user id was expected.
