### ISSUE TITLE
Help with getting my dev environment up and runnung.

### ISSUE THREAD

**Issue by geoff-cox** [RunestoneInteractive/rs#436]
@bnmnetp Thanks for your reply. I am just following up. I re-forked rs repo and attempted to initialize the database, but sadly, I got the same key-type error.

For reference, here is the error again:

```
WARN[0000] The "POSTGRESQL_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRESQL_DATABASE" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRESQL_DATABASE" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRESQL_USERNAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRESQL_PASSWORD" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOAD_BALANCER_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOAD_BALANCER_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_SERVER" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_LOGIN" variable is not set. Defaulting to a blank string.
WARN[0000] The "SPACES_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "SPACES_SECRET" variable is not set. Defaulting to a blank string.
[+] Building 0.0s (0/0)                                                                                  docker:default
WARN[0000] Found orphan containers ([rs-db-1]) for this project. If you removed or renamed this service in your 
compose file, you can run this command with the --remove-orphans flag to clean it up.
[+] Building 0.0s (0/0)                                                                                  docker:default
INFO - 2023-11-21 23:34:19,728 - Settings - Error path is /usr/books/tickets
You may want to define the DC_DEV_DBURL environment variable
You may want to define the DC_DBURL environment variable
Using configuration: development
Using database: runestone_dev
RUNESTONE_PATH is /usr/src/app
BOOK_PATH is /usr/books
SERVER_CONFIG is development
WEB2PY_CONFIG is development
The database URL is configured as postgresql+asyncpg://runestone:runestone@db/runestone_dev
DBNAME is runestone_dev
Checking database connection
postgresql+asyncpg://runestone:runestone@db/runestone_dev
Database connection successful
You may want to define the DC_DEV_DBURL environment variable
You may want to define the DC_DBURL environment variable
Initializing the database
/usr/local/lib/python3.10/site-packages/pydantic/main.py:308: UserWarning: Pydantic serializer warnings:
  Expected `bool` but got `ColumnDefault` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
ERROR - 2023-11-21 23:34:22,100 - read_key - No Key file is found will default to settings.jwt_secret
Traceback (most recent call last):
  File "/usr/local/bin/rsmanage", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1157, in __call__
    return anyio.run(self._main, main, args, kwargs, **opts)
  File "/usr/local/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 68, in run
    return asynclib.run(func, *args, **backend_options)
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 204, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 199, in wrapper
    return await func(*args)
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1160, in _main
    return await main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1076, in main
    rv = await self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1687, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1434, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 780, in invoke
    rv = await rv
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 780, in invoke
    rv = await rv
  File "/usr/local/lib/python3.10/site-packages/rsptx/rsmanage/core.py", line 240, in initdb
    await _initdb(config)
  File "/usr/local/lib/python3.10/site-packages/rsptx/rsmanage/core.py", line 183, in _initdb
    await create_initial_courses_users()
  File "/usr/local/lib/python3.10/site-packages/rsptx/db/crud.py", line 912, in create_initial_courses_users
    await create_user(
  File "/usr/local/lib/python3.10/site-packages/rsptx/db/crud.py", line 615, in create_user
    new_user.password = str(crypt(user.password)[0])
  File "/usr/local/lib/python3.10/site-packages/pydal/validators.py", line 4276, in __str__
    if ":" in self.crypt.key:
TypeError: a bytes-like object is required, not 'str'
```

**Comment by bnmnetp** [comment]
Hmmm, that is a different path and I think a different error.  Looks easy enough to fix.   But I probably can't get to it until later today.

I don't think this is fatal for your testing purposes, you can just register a user from the initial web page.

**Comment by bnmnetp** [comment]
Also, you can avoid this error by setting a WEB2PY_PRIVATE_KEY environment variable otherwise it defaults back to a setting that now must be a bytes type variable.  working on a fix so that we cast it to a str when needed.

**Comment by geoff-cox** [comment]
I synced my fork with the latest update and ran `initdb` again.  The key error appears to be gone and I received the following log:

```
WARN[0000] The "POSTGRESQL_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRESQL_DATABASE" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRESQL_DATABASE" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRESQL_USERNAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRESQL_PASSWORD" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOAD_BALANCER_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOAD_BALANCER_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_SERVER" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_LOGIN" variable is not set. Defaulting to a blank string.
WARN[0000] The "SPACES_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "SPACES_SECRET" variable is not set. Defaulting to a blank string.
[+] Building 0.0s (0/0)                                                                                  docker:default
WARN[0000] Found orphan containers ([rs-db-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
[+] Building 0.0s (0/0)                                                                                  docker:default
INFO - 2023-11-23 19:51:09,913 - Settings - Error path is /usr/books/tickets
You may want to define the DC_DEV_DBURL environment variable
You may want to define the DC_DBURL environment variable
Using configuration: development
Using database: runestone_dev
RUNESTONE_PATH is /usr/src/app
BOOK_PATH is /usr/books
SERVER_CONFIG is development
WEB2PY_CONFIG is development
The database URL is configured as postgresql+asyncpg://runestone:runestone@db/runestone_dev
DBNAME is runestone_dev
Checking database connection
postgresql+asyncpg://runestone:runestone@db/runestone_dev
Database connection successful
You may want to define the DC_DEV_DBURL environment variable
You may want to define the DC_DBURL environment variable
Initializing the database
/usr/local/lib/python3.10/site-packages/pydantic/main.py:308: UserWarning: Pydantic serializer warnings:
  Expected `bool` but got `ColumnDefault` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
ERROR - 2023-11-23 19:51:11,916 - read_key - No Key file is found will default to settings.jwt_secret
```

Then, when running rsmanage env (within the poetry shell), I received the error below. It looks like it is having trouble importing the `psycopg` modules. I do see that poetry installed it however.

```
 Traceback (most recent call last):
  File "/home/gcox/textbook-dev/runestone/rs/.venv/bin/rsmanage", line 5, in <module>
    from rsptx.rsmanage.core import cli
  File "/home/gcox/textbook-dev/runestone/rs/bases/rsptx/rsmanage/__init__.py", line 1, in <module>
    from rsptx.rsmanage import core
  File "/home/gcox/textbook-dev/runestone/rs/bases/rsptx/rsmanage/core.py", line 28, in <module>
    from pgcli.main import cli as clipg
  File "/home/gcox/textbook-dev/runestone/rs/.venv/lib/python3.10/site-packages/pgcli/main.py", line 2, in <module>
    from pgspecial.namedqueries import NamedQueries
  File "/home/gcox/textbook-dev/runestone/rs/.venv/lib/python3.10/site-packages/pgspecial/__init__.py", line 12, in <module>
    from . import dbcommands
  File "/home/gcox/textbook-dev/runestone/rs/.venv/lib/python3.10/site-packages/pgspecial/dbcommands.py", line 7, in <module>
    from psycopg.sql import SQL
  File "/home/gcox/textbook-dev/runestone/rs/.venv/lib/python3.10/site-packages/psycopg/__init__.py", line 9, in <module>
    from . import pq  # noqa: F401 import early to stabilize side effects
  File "/home/gcox/textbook-dev/runestone/rs/.venv/lib/python3.10/site-packages/psycopg/pq/__init__.py", line 114, in <module>
    import_from_libpq()
  File "/home/gcox/textbook-dev/runestone/rs/.venv/lib/python3.10/site-packages/psycopg/pq/__init__.py", line 106, in import_from_libpq
    raise ImportError(
ImportError: no pq wrapper available.
Attempts made:
- couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation: libpq library not found
```

Running `env` through docker with `docker compose run rsmanage rsmanage --verbose env` seems to do ok. See output below.

```
WARN[0000] The "POSTGRESQL_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRESQL_DATABASE" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRESQL_DATABASE" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRESQL_USERNAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRESQL_PASSWORD" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOAD_BALANCER_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOAD_BALANCER_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_SERVER" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_LOGIN" variable is not set. Defaulting to a blank string.
WARN[0000] The "SPACES_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "SPACES_SECRET" variable is not set. Defaulting to a blank string.
[+] Building 0.0s (0/0)                                                                                  docker:default
WARN[0000] Found orphan containers ([rs-db-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
[+] Building 0.0s (0/0)                                                                                  docker:default
INFO - 2023-11-23 19:57:10,183 - Settings - Error path is /usr/books/tickets
You may want to define the DC_DEV_DBURL environment variable
You may want to define the DC_DBURL environment variable
Using configuration: development
Using database: runestone_dev
RUNESTONE_PATH is /usr/src/app
BOOK_PATH is /usr/books
SERVER_CONFIG is development
WEB2PY_CONFIG is development
The database URL is configured as postgresql+asyncpg://runestone:runestone@db/runestone_dev
DBNAME is runestone_dev
Checking database connection
postgresql+asyncpg://runestone:runestone@db/runestone_dev
Database connection successful
RUNESTONE_PATH is /usr/src/app
BOOK_PATH is /usr/books
SERVER_CONFIG is development
WEB2PY_CONFIG is development
The database URL is configured as postgresql+asyncpg://runestone:runestone@db/runestone_dev
DBNAME is runestone_dev
Exiting with result of 0
```
