### ISSUE TITLE
initial build error

### ISSUE THREAD

**Issue by wrigjl** [RunestoneInteractive/rs#576]
**What Course are you in**
monorepo build

**Describe the bug**

I've got poetry install, nodejs, and npm and a freshly cloned repo.

```
  179  git clone https://github.com/RunestoneInteractive/rs.git
  180  cd rs
  181  cp sample.env .env
  182  vi .env
  183  poetry install --with=dev
  184  poetry shell
  185  build full
```

Error reported:

```
assignment │ Fail See ./projects/assignment_server/build.log
```

Error log:

```
Build log for assignment on 2024-11-13 08:16:32.130213
^[[33mThe CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.^[[39m
error during build:
Error: ENOENT: no such file or directory, stat '/Users/jason/rs/bases/rsptx/assignment_server_api/assignment_builder/public/runestone'
    at Object.statSync (node:fs:1658:25)
    at copyDir (file:///Users/jason/rs/bases/rsptx/assignment_server_api/assignment_builder/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:12453:27)
    at prepareOutDir (file:///Users/jason/rs/bases/rsptx/assignment_server_api/assignment_builder/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:66950:13)
    at build (file:///Users/jason/rs/bases/rsptx/assignment_server_api/assignment_builder/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:66895:13)
    at async CAC.<anonymous> (file:///Users/jason/rs/bases/rsptx/assignment_server_api/assignment_builder/node_modules/vite/dist/node/cli.js:842:9)
Traceback (most recent call last):
  File "/Users/jason/rs/projects/assignment_server/build.py", line 13, in <module>
    subprocess.run(["npm", "run", "build"], check=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
```

Looks like the directory pointed to by the symlink isn't being created:

```
(rs-py3.11) jason@Jasons-MacBook-Pro rs % ls -l /Users/jason/rs/bases/rsptx/assignment_server_api/assignment_builder/public/runestone
lrwxr-xr-x  1 jason  staff  36 Nov 13 08:14 /Users/jason/rs/bases/rsptx/assignment_server_api/assignment_builder/public/runestone -> ../../../interactives/runestone/dist
(rs-py3.11) jason@Jasons-MacBook-Pro rs % ls -l /Users/jason/rs/bases/rsptx/interactives/runestone/dist
ls: /Users/jason/rs/bases/rsptx/interactives/runestone/dist: No such file or directory
```

This "fixes" it:

```
mkdir /Users/jason/rs/bases/rsptx/interactives/runestone/dist
```

**Comment by bnmnetp** [comment]
A `build full` just builds the "core" services: runestone, book, assignment, nginx.  Maybe I should have kept interactives as a part of the core services.  But I think a better solution is to have core check to make sure that folder exists, and if not, then keep interactives in the list of services to build.

I don't want to say that people should do a `build --all` for a brand new checkout as the author server takes a LONG time to build as it assembles 6GB worth of LaTeX stuff.

So, I'll have the above implemented shortly.

**Comment by wrigjl** [comment]
can confirm that c769b3584fa7838fbd09f56a2264f8e6f11130ef fixed it.
