### ISSUE TITLE
I could not see the quiz summary

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/rs#81]
Error reported in course fall2020rosen on page /runestone/exams/one_exam_competency?assignment=Chapter%202%20Quiz by user ProfRosen andrew.rosen@temple.edu
    Please describe what you were doing that led up to this error:

    ---------------- Traceback --------------
    Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/exams.py", line 112, in <module>
  File "/home/bmiller/Runestone/web2py/gluon/globals.py", line 421, in <lambda>
    self._caller = lambda f: f()
  File "/home/bmiller/Runestone/web2py/gluon/tools.py", line 3869, in f
    return action(*a, **b)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/exams.py", line 83, in one_exam_competency
    pcdata = c.to_json()
  File "/home/bmiller/.local/lib/python3.7/site-packages/altair/utils/schemapi.py", line 339, in to_json
    dct = self.to_dict(validate=validate, ignore=ignore, context=context)
  File "/home/bmiller/.local/lib/python3.7/site-packages/altair/vegalite/v4/api.py", line 365, in to_dict
    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)
  File "/home/bmiller/.local/lib/python3.7/site-packages/altair/utils/schemapi.py", line 299, in to_dict
    validate=sub_validate, context=context)
  File "/home/bmiller/.local/lib/python3.7/site-packages/altair/utils/schemapi.py", line 60, in _todict
    return {k: _todict(v, validate, context) for k, v in obj.items()
  File "/home/bmiller/.local/lib/python3.7/site-packages/altair/utils/schemapi.py", line 61, in <dictcomp>
    if v is not Undefined}
  File "/home/bmiller/.local/lib/python3.7/site-packages/altair/utils/schemapi.py", line 56, in _todict
    return obj.to_dict(validate=validate, context=context)
  File "/home/bmiller/.local/lib/python3.7/site-packages/altair/utils/schemapi.py", line 299, in to_dict
    validate=sub_validate, context=context)
  File "/home/bmiller/.local/lib/python3.7/site-packages/altair/utils/schemapi.py", line 60, in _todict
    return {k: _todict(v, validate, context) for k, v in obj.items()
  File "/home/bmiller/.local/lib/python3.7/site-packages/altair/utils/schemapi.py", line 61, in <dictcomp>
    if v is not Undefined}
  File "/home/bmiller/.local/lib/python3.7/site-packages/altair/utils/schemapi.py", line 56, in _todict
    return obj.to_dict(validate=validate, context=context)
  File "/home/bmiller/.local/lib/python3.7/site-packages/altair/vegalite/v4/schema/channels.py", line 44, in to_dict
    "match any column in the data.".format(shorthand))
ValueError: competency encoding field is specified without a type; the type cannot be inferred because it does not match any column in the data.

**Comment by bnmnetp** [comment]
Closing due to old age. likely already fixed or not applicable anymore
